# Generated by Django 4.0 on 2022-02-11 00:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplarlivro',
            old_name='editoto',
            new_name='editora',
        ),
        migrations.AddField(
            model_name='exemplarlivro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='exemplarlivro',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificador único para este exemplar em toda a biblioteca.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exemplarlivro',
            name='situacao',
            field=models.CharField(blank=True, choices=[('m', 'Manutencao'), ('e', 'Emprestado'), ('d', 'Disponivel'), ('r', 'Reservado')], default='m', help_text='Situação do exemplar', max_length=1),
        ),
    ]
